@startuml
title RF PAN3060\nBFT System

' #bft_station_e290 always on the right side
participant bft_device_e290 as "BFT Device" << <img:./image/bft-device.png{scale=0.1}> >>

participant bft_station_e290 as "BFT Station" << <img:./image/bft-station.png{scale=0.1}> >>
participant bft_server as "BFT Server" << <img:./image/bft-server.png{scale=0.05}> >>

alt normal opereation
bft_station_e290 -> bft_station_e290: wait to\nreceive data
bft_device_e290 -> bft_station_e290: transmit data
bft_station_e290 -> bft_station_e290: check data\nreceived
bft_station_e290 -> bft_server: forward data
bft_server --> bft_station_e290: ack received
bft_station_e290 --> bft_device_e290: ack received

else failure case

group bft-station not respond
bft_station_e290 -> bft_station_e290: wait to\nreceive data
bft_device_e290 -> bft_station_e290: transmit data
bft_device_e290 -> bft_device_e290: wait for next\ntransmit
bft_device_e290 -> bft_station_e290: transmit data
bft_station_e290 -> bft_station_e290: check data\nreceived
bft_station_e290 -> bft_server: forward data

end

group bft-monitor-app (client) not activate
bft_station_e290 -> bft_station_e290: wait to\nreceive data
bft_device_e290 -> bft_station_e290: transmit data
bft_station_e290 -> bft_station_e290: check data\nreceived
bft_station_e290 -> bft_server: forward data
bft_server --> bft_station_e290: client not connected
bft_station_e290 --> bft_device_e290: ack client not connected
end

end


' bft_

' bft_station_e290 -> bft_station_e290
' bft_device_e290 -> bft_station_e290: e290_demo_transmit
' bft_station_e290 -> bft_server: Update bft_device gps data


@enduml